const STORAGE_KEY='cowlsly-chat-demo-v1';
const seed={active:'marla',sound:false,reducedMotion:false,chats:[{id:'marla',name:'Marla',type:'ai',status:'Online · AI contact',muted:false,blocked:false,messages:[{id:'m1',mine:false,text:'Hi Cowy — this is the Cowlsly Chat demo shell. Nothing here leaves this browser.',at:Date.now()-3600000,state:'read'},{id:'m2',mine:true,text:'Good. Keep it clear and simple.',at:Date.now()-3500000,state:'read'}]},{id:'support',name:'Cowlsly Support',type:'person',status:'Demo contact',muted:false,blocked:false,messages:[{id:'s1',mine:false,text:'Welcome to the messenger preview. Use the controls to test the interaction model.',at:Date.now()-7200000,state:'delivered'}]}]};
const load=()=>{try{return {...seed,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(seed)}};
let state=load(); let replyTo=null; let editingId=null;
const $=s=>document.querySelector(s); const shell=$('.app-shell'); const list=$('#conversation-list'); const messages=$('#messages'); const input=$('#message-input');
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const active=()=>state.chats.find(c=>c.id===state.active)||state.chats[0];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(text){const t=$('#toast');t.textContent=text;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,1800)}
function renderList(filter=''){list.innerHTML='';state.chats.filter(c=>c.name.toLowerCase().includes(filter.toLowerCase())).forEach(c=>{const last=c.messages.at(-1);const b=document.createElement('button');b.type='button';b.className='chat-row'+(c.id===state.active?' active':'');b.innerHTML=`<span class="row-avatar">${esc(c.name[0]||'?')}</span><span class="row-main"><strong>${esc(c.name)}${c.muted?' · 🔇':''}</strong><span>${esc(last?.text||'No messages yet')}</span></span><time>${last?new Date(last.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</time>`;b.onclick=()=>{state.active=c.id;save();render();shell.classList.add('chat-open')};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="empty">No matching conversations.</div>'}
function renderMessages(){const c=active();messages.innerHTML='';const q=$('#message-search-input').value.trim().toLowerCase();const rows=c.messages.filter(m=>!q||m.text.toLowerCase().includes(q));rows.forEach(m=>{const el=document.createElement('article');el.className='message'+(m.mine?' mine':'');el.tabIndex=0;const quote=m.replyText?`<div class="quoted">${esc(m.replyText)}</div>`:'';el.innerHTML=`${quote}<div>${esc(m.text)}</div><div class="meta"><span>${new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span>${esc(m.state||'sent')}</span>${m.saved?'<span>★</span>':''}</div><div class="message-actions"><button data-act="reply" aria-label="Reply">↩</button>${m.mine?'<button data-act="edit" aria-label="Edit">✎</button>':''}<button data-act="copy" aria-label="Copy">⧉</button><button data-act="save" aria-label="Save">★</button>${m.mine?'<button data-act="delete" aria-label="Delete">×</button>':''}</div>`;el.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>messageAction(m,b.dataset.act));messages.appendChild(el)});if(!rows.length)messages.innerHTML='<div class="empty">No messages found.</div>';requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight)}
function renderHeader(){const c=active();$('#active-name').textContent=c.name;$('#active-status').textContent=(c.blocked?'Blocked · ':c.muted?'Muted · ':'')+c.status;$('#active-avatar').textContent=c.name[0]||'?'}
function render(){renderList($('#search').value);renderHeader();renderMessages();document.body.classList.toggle('reduced-motion',!!state.reducedMotion);$('#sound-toggle').setAttribute('aria-pressed',String(!!state.sound));$('#motion-toggle').setAttribute('aria-pressed',String(!!state.reducedMotion))}
function messageAction(m,act){const c=active();if(act==='reply'){replyTo=m;editingId=null;$('#reply-banner').hidden=false;$('#reply-text').textContent=m.text;input.focus()}if(act==='edit'){editingId=m.id;replyTo=null;$('#reply-banner').hidden=false;$('#reply-text').textContent='Editing your message';input.value=m.text;input.focus()}if(act==='copy'){navigator.clipboard?.writeText(m.text);toast('Copied')}if(act==='save'){m.saved=!m.saved;save();renderMessages();toast(m.saved?'Saved':'Unsaved')}if(act==='delete'){c.messages=c.messages.filter(x=>x.id!==m.id);save();render();toast('Message deleted')}}
$('#composer').addEventListener('submit',e=>{e.preventDefault();const c=active();const text=input.value.trim();if(!text||c.blocked)return;if(editingId){const m=c.messages.find(x=>x.id===editingId);if(m){m.text=text;m.edited=true;m.at=Date.now()}editingId=null}else{c.messages.push({id:crypto.randomUUID(),mine:true,text,replyText:replyTo?.text||'',at:Date.now(),state:'sent'});setTimeout(()=>{const m=c.messages.at(-1);if(m?.mine){m.state='delivered';save();renderMessages()}},550)}replyTo=null;$('#reply-banner').hidden=true;input.value='';save();render();if(state.sound)navigator.vibrate?.(18)});
$('#cancel-reply').onclick=()=>{replyTo=null;editingId=null;$('#reply-banner').hidden=true;input.value=''};
$('#search').oninput=e=>renderList(e.target.value);
$('#back').onclick=()=>shell.classList.remove('chat-open');
$('#new-chat').onclick=()=>$('#new-chat-dialog').showModal();
$('#create-chat').onclick=e=>{e.preventDefault();const name=$('#new-chat-name').value.trim();if(!name)return;const id=crypto.randomUUID();state.chats.unshift({id,name,type:$('#new-chat-type').value,status:$('#new-chat-type').value==='ai'?'AI contact':'New contact',muted:false,blocked:false,messages:[]});state.active=id;save();$('#new-chat-dialog').close();$('#new-chat-name').value='';render();shell.classList.add('chat-open')};
$('#sound-toggle').onclick=()=>{state.sound=!state.sound;save();render();toast(state.sound?'Sounds on':'Sounds off')};
$('#motion-toggle').onclick=()=>{state.reducedMotion=!state.reducedMotion;save();render();toast(state.reducedMotion?'Reduced motion on':'Reduced motion off')};
$('#search-messages').onclick=()=>{const bar=$('#message-search-bar');bar.hidden=!bar.hidden;if(!bar.hidden)$('#message-search-input').focus()};
$('#close-message-search').onclick=()=>{$('#message-search-bar').hidden=true;$('#message-search-input').value='';renderMessages()};
$('#message-search-input').oninput=renderMessages;
$('#attach').onclick=()=>toast('Attachment flow is intentionally disabled in this demo');
$('#chat-menu').onclick=()=>{const c=active();const d=$('#action-dialog');$('#action-dialog-content').innerHTML=`<h2>${esc(c.name)}</h2><div class="menu-grid"><button class="pill-btn" data-menu="mute">${c.muted?'Unmute':'Mute'}</button><button class="pill-btn" data-menu="block">${c.blocked?'Unblock':'Block'}</button><button class="pill-btn" data-menu="report">Report</button><button class="pill-btn" data-menu="clear">Clear chat</button></div><div class="dialog-actions"><button class="pill-btn" data-menu="close">Close</button></div>`;$('#action-dialog-content').querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{const a=b.dataset.menu;if(a==='mute')c.muted=!c.muted;if(a==='block')c.blocked=!c.blocked;if(a==='report')toast('Demo report recorded locally only');if(a==='clear')c.messages=[];save();render();if(a!=='report')d.close()});d.showModal()};
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});
render();
